Master migration dan controller
zisapp/be_zisapp pull request #11
Opened 2021-06-09 07:32 UTC by agnisnafaz

master insya allah fix 
aamiin ya Allah :)

2021-06-09 11:34 UTC, triandamai commented on app/Http/Controllers/BankController.php
> +        $delete = $bank->delete();
alangkah lebih baik ditambahin untuk ngecek apakah datanya ada atau tidak kalau ada berarti lanjut hapus kalo gaada langsung ngirim pesan gagal karena data tidak ditemukan

2021-06-09 11:35 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
>          $pengguna = Pengguna::find($id);
ini juga dicek apakah datanya ada? kalau ada baru lanjut hapus

2021-06-09 11:35 UTC, triandamai requested changes
validationnya jangan lupa

2021-06-10 04:01 UTC, agnisnafaz commented on app/Http/Controllers/BankController.php
> +        $delete = $bank->delete();
ini ngeceknya kaya yang di login bukan mas?

2021-06-10 08:08 UTC, triandamai approved these changes
acc

2021-06-10 08:08 UTC, merged