Nyelesein master, tapi belom selesai.
zisapp/be_zisapp pull request #12
Opened 2021-06-11 16:12 UTC by agnisnafaz

Nyelesein master, tapi belom selesai.
Yuk semnagat yukkk

2021-06-12 07:44 UTC, triandamai commented on app/Http/Controllers/BankController.php
> +
//cek apakah bank dengan id = $id ada di database

2021-06-12 07:44 UTC, triandamai commented on app/Http/Controllers/BankController.php
> +            $update = $bank->update();
//proses update
//kemudian cek apakah prosesnya berhasil

2021-06-12 07:45 UTC, triandamai commented on app/Http/Controllers/BankController.php
>              $data['data'] = null;
kurang `$data['status']='', $data['message']`

2021-06-12 07:49 UTC, triandamai requested changes
mulai dikasih penjelasan ya pake komentar dikodingannya aku udah kasih contoh buat bantu orang baca kodinganmu dan memahami alurnya(dokumentasi)

dan jangan lupa `$data['status'], $data['message'], $data['data']`

2021-06-12 07:54 UTC, triandamai commented on app/Http/Controllers/BankController.php
> +
ini contohnya

2021-06-12 07:54 UTC, triandamai commented on app/Http/Controllers/BankController.php
> +            $update = $bank->update();
ini juga

2021-06-12 12:24 UTC, agnisnafaz commented on app/Http/Controllers/BankController.php
> +
```php
protected $primaryKey = 'id_pengguna';
```

kaya gitukan mas?

2021-06-13 13:23 UTC, triandamai commented on app/Http/Controllers/BankController.php
>          return $data;
kurang `$data['message']`

2021-06-13 13:25 UTC, triandamai approved these changes
acc

2021-06-13 13:25 UTC, merged

2021-06-13 14:14 UTC, triandamai commented
done