Master Akun buat di Menu Transaksi
zisapp/be_zisapp pull request #14
Opened 2021-06-15 08:40 UTC by agnisnafaz

maaf baru segituu, ntar lanjoot lagi ya mas
makasii

2021-06-15 12:23 UTC, triandamai commented on app/Http/Controllers/AkunController.php
> +        $akun = Akun::find($id);
Kebalik `find()` dulu baru ambil requestnya

2021-06-17 14:38 UTC, triandamai commented on app/Http/Controllers/AkunController.php
> +
```php
    $data['status'] = ''
    $data['message'] = ''
    $data['data'] = ''
```

kurang ini

2021-06-17 14:39 UTC, triandamai commented on app/Http/Controllers/AkunController.php
> +                $Data['data'] = null;
typo `$data` bukan `$Data`

2021-06-17 14:40 UTC, triandamai commented on app/Http/Controllers/AkunController.php
> +            $data['data'] = null;
`$data['message']`
`$data['status']`

kurang ini

2021-06-17 14:41 UTC, triandamai commented on app/Http/Controllers/KasController.php
> +        $data = DB::select("SELECT *FROM kass LEFT JOIN akuns ON kass.id_akun = akuns.id_akun");
`$data['message']`
`$data['status']`
`$data['data']`

2021-06-17 14:42 UTC, triandamai commented on app/Http/Controllers/KasController.php
> +            $data['data'] = null;
kurang `$data['message']` `$data['status']`

2021-06-17 14:43 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
>              $data['status_pengguna'] = false;
`$data['status']`

2021-06-17 14:43 UTC, triandamai requested changes
benerin dulu

2021-06-17 16:58 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
> +        $data['data'] = Pengguna::all(); //menampilkan semua data yang ada di tabel Pengguna
hapus aja

2021-06-17 16:59 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
> +        $data = DB::select("SELECT * FROM penggunas LEFT JOIN kantors ON penggunas.id_kantor = kantors.id_kantor"); //perintah menampilkan dua  table (relasi)->relasi antara table pengguna dan tabel
ganti `$data['data'] = DB::select(...`

2021-06-17 17:00 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
>                  $data['status_pengguna'] = true;
`$data['status']` aja

2021-06-17 17:00 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
>                  $data['status_pengguna'] = false;
`$data['status']` aja

2021-06-17 17:00 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
>                  $data['status_pengguna'] = false;
`$data['status']` aja

2021-06-17 17:00 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
>                  $data['status_pengguna'] = true;
`$data['status']` aja

2021-06-17 17:01 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
>              $data['status_pengguna'] = false;
`$data['status']` aja

2021-06-17 17:01 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
>              $data['status_pengguna'] = true;
`$data['status']` aja

2021-06-17 17:01 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
> +            $data['status_pengguna'] = false;
`$data['status']` aja

2021-06-17 17:04 UTC, triandamai requested changes
masih ada typo dan salah pemanggilan

2021-06-18 11:56 UTC, agnisnafaz commented on app/Http/Controllers/PenggunaController.php
> +        $data['data'] = Pengguna::all(); //menampilkan semua data yang ada di tabel Pengguna
mas, itu yang dihapus bagian ini semuanya?

<!--StartFragment--> 
$data['status_pengguna'] = 200; //menampilkan status        
$data['message'] = "Data Pengguna"; //menampilkan pesan        
$data['data'] = Pengguna::all(); //menampilkan semua data yang ada di tabel Pengguna
<!--EndFragment-->

2021-06-18 11:58 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
> +        $data['data'] = Pengguna::all(); //menampilkan semua data yang ada di tabel Pengguna
`$data['data'] = Pengguna::all();` ini aja

2021-06-18 11:59 UTC, agnisnafaz commented on app/Http/Controllers/PenggunaController.php
> +        $data['data'] = Pengguna::all(); //menampilkan semua data yang ada di tabel Pengguna
berarti cuma nampilin status sama messagenya aja ya mas?

2021-06-18 12:29 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
> +        $data['data'] = Pengguna::all(); //menampilkan semua data yang ada di tabel Pengguna
kan udah ada `$data['data'] = DB::select(...`

2021-06-18 12:29 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
> +        $data['data'] = Pengguna::all(); //menampilkan semua data yang ada di tabel Pengguna
dibawahnya

2021-06-18 12:41 UTC, agnisnafaz commented on app/Http/Controllers/PenggunaController.php
> +        $data['data'] = Pengguna::all(); //menampilkan semua data yang ada di tabel Pengguna
oke oke mas, makasii

2021-06-18 14:06 UTC, triandamai commented on app/Http/Controllers/master/PenggunaController.php
> +namespace App\Http\Controllers\master\Validator;
ini harusnya `use` bukan namespace, namespace

2021-06-18 14:12 UTC, triandamai commented on app/Http/Controllers/master/PenggunaController.php
> -use Illuminate\Support\Facades\Validator;
harusnya kaya gini

2021-06-20 09:25 UTC, agnisnafaz reviewed
mas, trian yang login belom jadi, maaf yaa

2021-06-20 12:10 UTC, triandamai approved these changes
nice and easy

2021-06-20 12:11 UTC, merged