migration table register
zisapp/be_zisapp pull request #2
Opened 2021-06-01 06:23 UTC by agnisnafaz

ini migration table register

2021-06-01 08:28 UTC, triandamai requested changes
untuk modelnya cukup 1 model aja

kan Register sama Login pakenya table user ? nah bikin aja `UserModel` jadi nanti controller `RegisterController` sama `LoginController` sama `UserController` pakenya 1 model(`UserModel`) dang ngga kebanyakan model

2021-06-01 08:34 UTC, triandamai requested changes
nama tablenya kok registers?

2021-06-01 08:34 UTC, triandamai commented on database/migrations/2021_06_01_070747_create_registers_table.php
> +        Schema::create('registers', function (Blueprint $table) {
table users kan?

2021-06-01 11:14 UTC, agnisnafaz commented on database/migrations/2021_06_01_070747_create_registers_table.php
> +        Schema::create('registers', function (Blueprint $table) {
mas trian mau tanyaa, ini kan jadinya nama tablenya users. Nah di laravel udah ada bawaannya namanya users juga. Jadi solusinya gimana ya?
makasiii

2021-06-01 16:41 UTC, triandamai commented on database/migrations/2021_06_01_070747_create_registers_table.php
> +        Schema::create('registers', function (Blueprint $table) {
Namain pengguna aja

2021-06-01 16:43 UTC, triandamai requested changes

2021-06-01 16:43 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
> +    }
Wkwkwk kalem2...ini maksudnya ambil semua data pengguna 

Jadi annti dihalaman datauser dapet datanya dari sini

2021-06-02 01:54 UTC, agnisnafaz commented on app/Http/Controllers/PenggunaController.php
> +    }
maksudnya itu show per id ya mas?

2021-06-02 01:55 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
> +    }
Ya intinya get all

2021-06-02 02:41 UTC, raflyfirdausy commented on app/Http/Controllers/PenggunaController.php
> +    }
Hi 😳

2021-06-02 04:24 UTC, triandamai commented on app/Http/Controllers/PenggunaController.php
> +    }
Opo gaes

2021-06-02 05:41 UTC, triandamai commented on routes/api.php
> +Route::post('pengguna', 'PenggunaController@login');
ini ganti aja login

jadinya `localhost:8000/login`


terus di postman username passwordnya di body

2021-06-02 05:42 UTC, triandamai commented on routes/api.php
> +Route::post('pengguna', 'PenggunaController@register');
ini juga jadiin register 
jadi 
`localhost:8000/register`

memang kita pakai controller yang sama tapi routenya bedain aja

2021-06-02 05:43 UTC, triandamai requested changes
coba fa biar nanti di postman ngetesnya enak

2021-06-02 05:44 UTC, triandamai commented on routes/api.php
> +Route::post('pengguna', 'PenggunaController@register');
jadinya gini
```php
Route::post('login','PenggunaController@login');
```

2021-06-02 10:20 UTC, triandamai commented on routes/api.php
> +Route::post('pengguna', 'PenggunaController@register');
untuk ngetesnya 

`localhost:8000/api/login`
`localhost:8000/api/register`
dst..

alasan: karena bikin routenya di file api.php jadinya ngetesnya ditampahin `api` (udah bener)
misal:
```php
Route::post('login','PenggunaController@login');
```
berarti tesnya `localhost:8000/api/login`

2021-06-02 10:21 UTC, triandamai commented on routes/api.php
> +Route::post('pengguna', 'PenggunaController@register');
ada error tapi

```sql
 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL: select * from `users` where `username` = sa limit 1)
```

2021-06-02 12:20 UTC, merged