Mustahik CRUD fix
zisapp/be_zisapp pull request #6
Opened 2021-06-04 13:20 UTC by agnisnafaz

mohon di cek kaka

2021-06-04 16:20 UTC, triandamai commented on routes/api.php
> +Route::put('/mustahik/{id}', 'MustahikController@update');
tidak perlu `/` diawal

2021-06-04 16:21 UTC, triandamai requested changes
hayuuuk

2021-06-05 02:59 UTC, agnisnafaz commented on routes/api.php
> +Route::put('/mustahik/{id}', 'MustahikController@update');
okeyyy siap

2021-06-06 10:40 UTC, triandamai approved these changes
Pass

2021-06-06 10:41 UTC, merged